version: '3'

services:
  globaleaks:
    build: .
    restart: unless-stopped
    container_name: globaleaks
    network_mode: bridge
    volumes:
       - ./volumes/globaleaks:/var/globaleaks
    ports:
      - 7780:8080
      - 7743:8443

volumes:
  globaleaks: